---
title: "Migrasi dan Inovasi"
author: "Anggota Kelompok
        <br>-Al Nazirul Mubin
        <br>-Bayu Angkasa Putra
        <br>-Muhammad Al Fatih
        <br>-Fairuz Azzahira
        <br>-Syarifa Rizkyna"
date: "2024"
output:
  revealjs::revealjs_presentation:
    theme: solarized
    transition: slide
    self_contained: true
    css: slides.css
  beamer_presentation:
    toc: false
    incremental: false
---

## Pengantar Migrasi dan Inovasi

<<<<<<< HEAD
Setelah kita belajar beberapa kerangka kerja yang dapat membantu Anda dalam mempersiapkan proses migrasi ke AWS, sekarang mari kita lihat bagaimana cara implementasinya
=======
**Tujuan Pembelajaran**

>1. Migrasi dan inovasi di AWS Cloud.

>2. AWS Cloud Adoption Framework (AWS CAF).

>3. Enam faktor utama dari strategi migrasi cloud.

>4. Manfaat dari solusi migrasi data AWS, seperti AWS Snowcone, AWS Snowball, dan AWS Snowmobile.

>5. Cakupan luas dari solusi inovatif yang ditawarkan AWS.
>>>>>>> f4514bd60c2547b8a65c918d3b3398eed513cd03

Proses migrasi tak terjadi hanya dengan menjentikkan jari lalu seketika semua elemen dari data center on-premise berjalan di AWS.

<<<<<<< HEAD
Setiap aplikasi yang berarsitektur tightly coupled  yang telah di bahas di Modul sebelumnya memiliki 6 kemungkinan opsi terkait strategi migrasi, AWS menyebutnya dengan 6 R.
=======
## Pengantar Migrasi dan Inovasi

**Pengenalan ke Migrasi dan Inovasi**

AWS menyediakan berbagai layanan migrasi yang dapat membantu Anda memindahkan beban kerja dari pusat data on-premise ke AWS Cloud. Beberapa layanan migrasi yang disediakan oleh AWS antara lain:

>1. AWS Server Migration Service (SMS): Layanan ini memungkinkan Anda untuk mengotomatiskan proses migrasi beban kerja yang berjalan di server fisik, virtual, atau cloud lain ke AWS. Layanan ini dapat membantu Anda dalam mengurangi downtime dan kompleksitas migrasi.
>>>>>>> f4514bd60c2547b8a65c918d3b3398eed513cd03

## Rehosting

Rehosting juga dikenal sebagai lift and shift (angkat dan pindahkan). Opsi ini mudah dilakukan karena Anda tak perlu membuat perubahan apa pun. Cukup pindahkan aplikasi yang Anda miliki ke AWS.
Dengan rehosting, Anda bisa menghemat hingga 30% dari total biaya walaupun tidak ada pengoptimalan apa pun pada aplikasi Anda.

## Replatforming

Strategi migrasi yang satu ini disebut juga dengan lift, tinker, and shift (angkat, perbaiki, dan pindahkan). Pada dasarnya, opsi ini masih berupa lift and shift namun Anda dapat melakukan beberapa pengoptimalan cloud. Dalam strategi ini, Anda tak akan mengubah arsitektur inti (core architecture) apa pun pada proses migrasi aplikasi.

## Retiring

AWS menemukan bahwa sebanyak 10% hingga 20% dari portofolio IT perusahaan menyertakan aplikasi yang tak lagi digunakan dan bisa dimatikan.
Menghapus aplikasi yang tidak lagi digunakan, menghemat biaya dan memfokuskan tim pada aplikasi yang aktif digunakan.

## Retaining

Saat hendak melakukan migrasi ke AWS, mungkin Anda memiliki beberapa aplikasi yang akan segera deprecated (dihentikan). Tetapi, aplikasi tersebut masih perlu digunakan selama beberapa waktu.

Nah, daripada memindahkan aplikasi tersebut ke AWS, sebaiknya Anda hanya memigrasikan aplikasi yang sekiranya masuk akal dan berguna untuk bisnis

## Pengantar Migrasi dan Inovasi

>2. AWS Database Migration Service (DMS): Layanan ini memungkinkan Anda untuk memigrasikan database yang berjalan di berbagai platform ke AWS. DMS mendukung migrasi antara berbagai jenis database, termasuk Oracle, MySQL, PostgreSQL, dan SQL Server.


>3. AWS Snow Family: AWS Snow Family adalah serangkaian perangkat fisik yang dirancang untuk memindahkan data dalam skala besar ke dan dari AWS. Perangkat-perangkat ini dapat digunakan untuk memindahkan data yang sangat besar atau dalam kasus-kasus di mana koneksi internet yang cepat tidak tersedia.

## AWS Well-Architected Framework

AWS Well-Architected Framework dirancang untuk membantu memahami cara merancang dan mengoperasikan sistem yang andal, aman, efisien, dan hemat biaya di AWS Cloud. AWS Well-Architected Framework terdiri dari 5 pilar 

1. Operational Excellence (Keunggulan Operasional)

Berguna menjalankan dan memantau sistem untuk memberikan nilai bisnis serta terus meningkatkan proses dan prosedur. Pilar Operational Excellence mencakup bagaimana organisasi  mendukung tujuan bisnis, kemampuan untuk menjalankan beban secara efektif.


## 
<div>
- Contohnya, melakukan operation as code (operasi sebagai kode), membuat anotasi dokumentasi, mengantisipasi kegagalan, dan sering memperbaiki prosedur operasi.

<br>
2. Security (Keamanan)

keamanan adalah prioritas utama AWS. Pilar ini melindungi informasi, sistem, dan aset Anda sekaligus memberikan nilai bisnis melalui risk assessment (penilaian risiko) dan strategi mitigasi.
</div>


## 

<div>

3. Reliability (Keandalan)

mencakup kemampuan sistem untuk memastikan beban kerja melakukan fungsi dengan benar dan konsisten sesuai harapan.

contohnya seperti :
<br>

- Pemulihan otomatis dari kegagalan infrastruktur atau layanan.
- Horizontal scaling--telah dibahas pada Modul Komputasi di Cloud--untuk meningkatkan ketersediaan beban kerja.
- Pengujian prosedur pemulihan.

</div>


## 

<div>
4. Performance Efficiency (Efisiensi Kinerja)

Pilar ini berfokus pada penggunaan sumber daya IT dan komputasi secara efisien untuk memenuhi kebutuhan.

Misalnya, menggunakan arsitektur serverless (tanpa server), melakukan eksperimen, dan merancang sistem agar dapat mendunia dalam hitungan menit.

<br>

5.Cost Optimization (Pengoptimalan Biaya) 

Pilar ini berfokus untuk mengontrol arah uang dibelanjakan guna menghindari biaya yang tak perlu.
contoh: 
menerapkan manajemen keuangan cloud, menganalisis pengeluaran, dan menggunakan managed service (layanan terkelola) untuk mengurangi biaya kepemilikan.
</div>

## Strategi Migrasi

Setelah mempelajari beberapa materi sebelumnya, kita telah memeliki beberapa wawasan akan AWS,antara lain sebagai berikut:

>1. Layanan AWS
>2. Terminologi AWS
>3. Enam manfaat utama menggunakan AWS Cloud


## AWA Snow Family

>1. Mengubah pengeluaran di muka menjadi pengeluaran variabel

>2. Manfaatkan skala ekonomi yang masif

>3. Berhenti menebak kapasitas

>4. Tingkatkan kecepatan dan ketangkasan

>5. Hentikan biaya pengelolaan dan pemelihara data center

>6. Mendunia dalam hitungan menit



## Inovasi dengan AWS
